### ISSUE TITLE
您好,我正在使用您的gowebdav,希望增加多账户与匿名账户

### ISSUE THREAD

**Issue by 277383761** [immortalwrt/openwrt-gowebdav#1]
像vsftp一样支持多账户与匿名账户功能.内样我就可以用webdav取代ftp了.
因为webdav传输速度比ftp快,而且挂载到macos下面支持读写,而ftp默认只读不可写

**Comment by gyj1109** [comment]
附议

**Comment by 1715173329** [comment]
gowebdav 实现上无法支持多用户，可以参考 webdav-go。
