### ISSUE TITLE
感觉gowebdav性能有点问题

### ISSUE THREAD

**Issue by LoogCP** [immortalwrt/openwrt-gowebdav#4]
以前用的是nginx的webdav，在使用zerotier远程访问路由器的webdav的时候，速度很快，但是因为路由器没有公网ip我不知道怎么配置ssl，然后居然nginx+frp会有问题，就换用uhttpd+gowebdav+frpc/zerotier，然后不管是通过frp还是zerotier访问webdav，在访问文件和传输性能上面远远落后于nginx方案
不知道是gowebdav性能比不上nginx还是说有些设置我没弄，麻烦大神解答一下

**Comment by 1715173329** [comment]
至少可以达到 1 Gbit/s，再高我也没有设备测。

**Comment by LoogCP** [comment]
> 至少可以达到 1 Gbit/s，再高我也没有设备测。

局域网性能没问题，但是和内网穿透配合起来就有问题了

**Comment by 1715173329** [comment]
That's not in my consideration.
